### ISSUE TITLE
请问这个项目是模拟 Kindle 样式还是用于适配 Kindle 浏览器网页？

### ISSUE THREAD

**Issue by hectorqin** [RiverTwilight/kindle-ui#2]
如题，这个项目的组件兼容 Kindle 浏览器吗？

**Comment by rivertwilight** [comment]
> 如题，这个项目的组件兼容 Kindle 浏览器吗？

是模仿样式，Kindle浏览器无法正常显示，基于React的。

**Comment by hectorqin** [comment]
Preact 不是可以通过 Polyfill 兼容 ie7，ie8 吗？考虑兼容一下吗？

**Comment by rivertwilight** [comment]
> Preact 不是可以通过 Polyfill 兼容 ie7，ie8 吗？考虑兼容一下吗？

我觉得可以，但短期内可能太忙没法弄
